### ISSUE TITLE
nyaml2nxdl xref edge cases

### ISSUE THREAD

**Issue by lukaspie** [FAIRmat-NFDI/nexus_definitions#115]
When using the new xref feature, I came across an edge case when adding the following docstring: 
```yaml
(NXinstrument):
    doc: 
     - |
      MPES spectrometer
     - | 
      xref:
        spec: ISO 18115-1:2023
        term: 12.58
        url: https://www.iso.org/obp/ui/en/#iso:std:iso:18115:-1:ed-3:v1:en:term:12.58
```
which is translated to
```xml
<group type="NXinstrument">
      <doc>
           MPES spectrometer
           
               This concept is related to term `12.58`_ of the ISO 18115-1:2023 standard.
           .. _12.58: NO URL
      </doc>
</group>
```
In this case, the problem is with the following line picking up `term:` in the url field and then not correctly reading the URL anymore.
https://github.com/FAIRmat-NFDI/nexus_definitions/blob/1016aa054582323d44cfd215685639ef9d4605b8/dev_tools/nyaml2nxdl/nyaml2nxdl_forward_tools.py#L302

Suggestion by @domna was to use regex for checking for `spec`, `term`, and `url`. @mkuehbach also mentioned that first it should be checked that `xref` is present _before_ we check for the three sub-keywords.

Other edge cases:
- What happens if one of  `spec`, `term`, `url` is present more than once in _xref_?
- Multiple xrefs are supported, should be added to the test file `dev_tools/tests/data/doc_yaml2nxdl.yaml`.
