### ISSUE TITLE
Extend NXdata with axis names/physical quantities glossary

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/nexus_definitions#78]
- [x] Provide a glossary (in NXdata) of optional data axis names/physical quantities which could be used and made required in the inheriting appdefs
- [x] Have NXdata in NXdetector with notion of xpixel and ypixel as standard view on the data
- [x] Example of writing NXdata (include also in NXmpes documentation)
- [x] NXdata tutorial (see #77)

# Small example

```yaml
my_data(NXdata):
    doc: |
        Can use `energy`, `kx`, etc... as definied below
    energy:
        doc: this is the energy
    kx:
        doc: this is the x-axis of the momentum
```

```
my_data/@axes = ['energy', 'kx', 'spin']
```

[Meeting ref](https://github.com/FAIRmat-NFDI/data-modeling/blob/cf734b776735693f1568211972eac51560329abb/mpes/meetings/2023-10-04_NXdata.md)
