### ISSUE TITLE
Use @target attribute in NXresolution

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/nexus_definitions#84]
Currently, NXresolution uses its own NXlink base class. However, this is the same concept as the nexus @target attribute.

**Comment by lukaspie** [comment]
@domna what was your suggestion here?

Currently, we have 
```yaml
  formula_symbol_LINK(NXlink):
    doc: |
      A symbol linking to another path in this appdef
      to be referred to from the `resolution_formula` field.
    symbol:
      exists: optional
    path:
      exists: optional
  resolution_formula:
    doc: |
      A resolution formula to determine the resolution from a set of symbols as
      entered by the `formula_symbol_...` fields.
      The output unit should match the provided unit of this field.

NXlink(NXobject):
  symbol:
    doc: |
      The symbol by which to refer to this link, e.g., for formulas
  path:
    doc: |
      A valid path inside an instance of an application definition, i.e.,
      of the form /entry/instrument/my_part/my_field
```

Was your plan to do it like this?
```yaml
  formula_symbol_LINK(NX_CHAR):
    doc: |
      A symbol linking to another path in this appdef
      to be referred to from the `resolution_formula` field.
    symbol:
      exists: optional
    \@target:
      doc: |
        A valid path inside an instance of an application definition, i.e.,
        of the form /entry/instrument/my_part/my_field
      exists: optional
  resolution_formula(NX_CHAR):
    doc: |
      A resolution formula to determine the resolution from a set of symbols as
      entered by the `formula_symbol_...` fields.
      The output unit should match the provided unit of this field.
````
