### ISSUE TITLE
Add `xref` control in nyaml2nxdl

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/nexus_definitions#87]
Rule: In NXDL, you need to put a specific text at the end of the docstring to indicate a relationships to a foreign concept.
in nyaml, add field xref like this:
```yaml
xref:
  spec: <spec>
  term: <term>
  url: <url>
```
in nyaml2nxdl, this should be converted at the end of the docstring to:

```
    This concept is related to term `<term>`_ of the <spec> standard.
.. _<term>: <url>
```

[Meeting ref](https://github.com/FAIRmat-NFDI/data-modeling/blob/main/mpes/meetings/2023-10-19_ISO_compatibility.md)

**Comment by sanbrock** [comment]
As proposed in #86, Sandor, Sherjeel and Rubel agrees to use the keywords below "doc":

myfield:  
  doc:  
    xref:  
      spec:  
      term:  
      url:

**Comment by RubelMozumder** [comment]
```
doc: |
   "text"
    xref: 
         spec:
         term:
```
This is not possible, as yaml is treated as dict in python.
